# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy documents
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      - run: npm run docs:build
#      - run: echo 'vue-chartjs.org' > docs/.vuepress/dist/CNAME
 
      - name: Publish GitHub Page
        uses: crazy-max/ghaction-github-pages@v2.1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build directory to deploy
          build_dir: docs/.vuepress/dist
          # Write the given domain name to the CNAME file
          fqdn: 'vue-chartjs.org'
